### ISSUE TITLE
OSS release

### ISSUE THREAD

**Issue by pgavlin** [pulumi/esc#2]
This epic tracks open-sourcing this repository.

```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/esc/issues/71
- [x] Issues for major coming features
- [x] CI/CD integration
- [x] `esc` CLI releases
- [x] godoc for libraries
- [ ] https://github.com/pulumi/esc/issues/73
- [ ] https://github.com/pulumi/esc/issues/74
- [ ] https://github.com/pulumi/esc/issues/75
- [ ] https://github.com/pulumi/esc/issues/76
- [ ] https://github.com/pulumi/esc/issues/72
- [ ] https://github.com/pulumi/esc/issues/78
```

**Comment by lukehoban** [comment]
All work items complete - repo and releases are all available now.
